language: node_js
node_js:
  - 8.9.4
sudo: required

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('challenge-jazida') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS challenge-jazida;'
script:
  - export NODE_ENV=github
  - npm run integration-test
#   - istanbul cover node_modules/.bin/$}{}
#   - codecov
branches:
  only:
    - master
    - dev
